# ---------------- #
#   Main Configs   #
# ---------------- #
title: 云端散仙且行切悟
author: yuxing
subtitle: "You never fail, until you give up!"
description: "似水流年！......"
keywords: cloudcome
url: "https://openstacks.github.io"
date_format: "ordinal"
favicon: /favicon.ico
timezone: Asia/beijin
encoding: "utf-8"
source_code: https://github.com/openstacks/openstacks.github.io
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
#organization: IBM, Inc.
organization_url: https://openstacks.github.io
location: Beijing, China
email: 840814120@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基
  

  -
    href: /open-source/
    label: 开源

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
    - jekyll-sitemap
#    - jekyll-seo-tag
#    - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-feed
    - jemoji
#    - jekyll-mentions
    - jekyll-github-metadata
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: openstacks
#douban_username: 
#facebook_username: 
#weibo_username: openstacks
#zhihu_username: openstacks
#twitter_username: openstacks

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
disqus_username: openstacks

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-72449510-4
#baidu_tongji_id: cf8506e0ef223e57ff6239944e5d46a4

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, shell, Docker,Linux]
skill_mobile_app_keywords: [Java]
#skill_windows_keywords: []

# ---------------- #
# Github metadata  #
# ---------------- #
repository: openstacks/openstacks.github.io
